// Shared "runtime bag" for the useVoice hook split.
//
// useVoice is a ref-and-callback heavy infrastructure hook.  Most of its body
// used to be thin wrapper functions that bundle a few stable refs/setters and
// forward to a corresponding `*Runtime` helper under voice/.  To slim the hook
// down, those wrappers are now generated by factories (see voiceBindings,
// voiceConversationStarters, voiceLifecycleControls, voiceTestEntries).  Each
// factory takes a single VoiceRuntimeBag and returns a group of bound
// functions.
//
// The bag also carries mutable "holders" (lifecycleHolder / enginesHolder /
// bindingsHolder).  These solve the late-binding problem: bindings need to be
// able to reference lifecycle.startVoiceConversation (e.g. via the bus
// effects) even though lifecycle is built _after_ bindings.  Holders let
// callers grab the slot lazily — by the time anything actually fires, all
// slots are populated.

import type { Dispatch, MutableRefObject, SetStateAction } from 'react'
import type {
  AppSettings,
  TranslationKey,
  TranslationParams,
  VoicePipelineState,
  VoiceState,
  VoiceTraceEntry,
  WakewordRuntimeState,
} from '../../types'
import type { VoiceDiagnosticResult } from './diagnostics'
import type { HearingRuntime } from '../../features/hearing'
import type { ParaformerStreamSession } from '../../features/hearing/localParaformer.ts'
import type { SenseVoiceStreamSession } from '../../features/hearing/localSenseVoice.ts'
import type { TencentAsrStreamSession } from '../../features/hearing/tencentAsr'
import type { WakewordRuntimeController } from '../../features/hearing/wakewordRuntime.ts'
import type {
  AudioPlaybackQueue,
  SpeechLevelController,
  StreamAudioPlayer,
  VoiceSessionEvent,
  VoiceSessionState,
  VoiceSessionTransport,
} from '../../features/voice'
import type { VoiceBus } from '../../features/voice/bus'
import type { VoiceBusEvent } from '../../features/voice/busEvents'
import type { BrowserSpeechRecognition } from '../../lib'
import type { ParaformerConversationState } from './paraformerConversation'
import type { SenseVoiceConversationState } from './sensevoiceConversation'
import type { TencentConversationState } from './tencentConversation'
import type {
  ApiRecordingSession,
  SpeechInterruptMonitorSession,
  SpeechSegmentMeta,
  StreamingSpeechOutputController,
  UseVoiceContext,
  VadConversationSession,
  VoiceConversationOptions,
} from './types'

// ── Refs ────────────────────────────────────────────────────────────────────

export type VoiceRefs = {
  voiceStateRef: MutableRefObject<VoiceState>
  voiceSessionRef: MutableRefObject<VoiceSessionState>
  continuousVoiceActiveRef: MutableRefObject<boolean>
  suppressVoiceReplyRef: MutableRefObject<boolean>
  restartVoiceTimerRef: MutableRefObject<number | null>
  noSpeechRestartCountRef: MutableRefObject<number>
  recognitionRef: MutableRefObject<BrowserSpeechRecognition | null>
  apiRecordingRef: MutableRefObject<ApiRecordingSession | null>
  vadSessionRef: MutableRefObject<VadConversationSession | null>
  speechLevelControllerRef: MutableRefObject<SpeechLevelController | null>
  audioPlaybackQueueRef: MutableRefObject<AudioPlaybackQueue<SpeechSegmentMeta> | null>
  streamAudioPlayerRef: MutableRefObject<StreamAudioPlayer | null>
  activeStreamingSpeechOutputRef: MutableRefObject<StreamingSpeechOutputController | null>
  speechLevelValueRef: MutableRefObject<number>
  paraformerSessionRef: MutableRefObject<ParaformerStreamSession | null>
  paraformerConversationRef: MutableRefObject<ParaformerConversationState | null>
  sensevoiceSessionRef: MutableRefObject<SenseVoiceStreamSession | null>
  sensevoiceConversationRef: MutableRefObject<SenseVoiceConversationState | null>
  tencentAsrSessionRef: MutableRefObject<TencentAsrStreamSession | null>
  tencentConversationRef: MutableRefObject<TencentConversationState | null>
  speechInterruptMonitorRef: MutableRefObject<SpeechInterruptMonitorSession | null>
  wakewordRuntimeRef: MutableRefObject<WakewordRuntimeController | null>
  wakewordAcknowledgingRef: MutableRefObject<boolean>
  activeVoiceConversationOptionsRef: MutableRefObject<VoiceConversationOptions>
  assistantSpeechGenerationRef: MutableRefObject<number>
  interruptedSpeechGenerationRef: MutableRefObject<number | null>
  lastSubmittedVoiceContentRef: MutableRefObject<{ content: string; sentAt: number }>
}

// ── Setters ─────────────────────────────────────────────────────────────────

export type VoiceSetters = {
  setVoiceState: (next: VoiceState) => void
  setVoicePipeline: Dispatch<SetStateAction<VoicePipelineState>>
  setVoiceTrace: Dispatch<SetStateAction<VoiceTraceEntry[]>>
  setSpeechLevel: Dispatch<SetStateAction<number>>
  setContinuousVoiceActive: Dispatch<SetStateAction<boolean>>
  setLiveTranscript: Dispatch<SetStateAction<string>>
  setWakewordState: Dispatch<SetStateAction<WakewordRuntimeState>>
}

// ── Hook-owned callbacks ────────────────────────────────────────────────────

// These live in the hook (because they use useCallback / close over hook
// state) and are exposed to the factories via the runtime bag.
export type VoiceHookCallbacks = {
  showPetStatus: (message: string, duration?: number, dedupeWindowMs?: number) => void
  updateVoicePipeline: (
    step: VoicePipelineState['step'],
    detail: string,
    transcript?: string,
  ) => void
  appendVoiceTrace: (
    title: string,
    detail: string,
    tone?: VoiceTraceEntry['tone'],
  ) => void
  clearPendingVoiceRestart: () => void
  ensureSupportedSpeechInputSettings: (announce?: boolean) => AppSettings
  busEmit: (event: VoiceBusEvent) => void
  ti: (key: TranslationKey, params?: TranslationParams) => string
}

// ── Factory output groups ───────────────────────────────────────────────────

export type VoiceBindings = {
  // Session dispatch
  dispatchVoiceSession: (event: VoiceSessionEvent) => VoiceSessionState
  dispatchVoiceSessionAndSync: (event: VoiceSessionEvent) => VoiceSessionState
  beginVoiceListeningSession: (transport: VoiceSessionTransport) => VoiceSessionState
  // Speech level / tracking
  setSpeechLevelValue: (nextLevel: number) => void
  getSpeechLevelController: () => SpeechLevelController
  stopSpeechTracking: () => void
  // Continuous voice mode toggle
  setContinuousVoiceSession: (active: boolean) => void
  // Interruption / monitor
  interruptSpeakingForVoiceInput: () => boolean
  stopSpeechInterruptMonitor: () => void
  startSpeechInterruptMonitor: (
    speechGeneration: number,
    shouldResumeContinuousVoice: boolean,
  ) => Promise<void>
  // Recording / VAD teardown
  stopApiRecording: (cancel?: boolean) => void
  destroyVadSession: (session: VadConversationSession | null) => Promise<void>
  stopVadListening: (cancel?: boolean) => Promise<void>
  // Conversation state cleanup
  clearParaformerConversationState: () => void
  clearSenseVoiceConversationState: () => void
  clearTencentConversationState: () => void
  // Speech output plumbing
  stopActiveSpeechOutput: () => void
  getStreamAudioPlayer: () => StreamAudioPlayer
  getAudioPlaybackQueue: () => AudioPlaybackQueue<SpeechSegmentMeta>
  startSpeechOutput: (
    text: string,
    speechSettings: AppSettings,
    options?: {
      onStart?: () => void
      onEnd?: () => void
      onError?: (message: string) => void
    },
  ) => Promise<void>
  // No-speech restart counter
  resetNoSpeechRestartCount: () => void
  getNoSpeechRestartDelay: () => number
  // Pause helper
  pauseContinuousVoice: (message: string, statusText?: string) => void
  // Settings predicates
  shouldAutoRestartVoice: () => boolean
  shouldKeepContinuousVoiceSession: () => boolean
  canInterruptSpeech: () => boolean
  // Interrupted-flag helpers
  isSpeechInterrupted: (speechGeneration: number) => boolean
  clearSpeechInterruptedFlag: (speechGeneration: number) => void
  // Provider failover hooks
  applySpeechOutputProviderFallback: (providerId: string, statusText?: string) => AppSettings
  buildSpeechOutputFailoverCandidates: (
    settings: AppSettings,
  ) => ReturnType<typeof import('./providerFallbacks').buildSpeechOutputFailoverCandidatesRuntime>
  testSpeechInputReadiness: (draftSettings: AppSettings) => Promise<VoiceDiagnosticResult>
  // Composer / dedup helpers
  fillComposerWithVoiceTranscript: (transcript: string) => void
  shouldIgnoreRepeatedVoiceContent: (content: string) => boolean
  rememberSubmittedVoiceContent: (content: string) => void
  // Transcript handling
  handleRecognizedVoiceTranscript: (
    rawTranscript: string,
    options?: { traceId?: string },
  ) => Promise<boolean>
  handleVoiceListeningFailure: (message: string, errorCode?: string) => void
}

export type VoiceEngines = {
  startVadVoiceConversation: (
    transcribeMode: 'api' | 'local',
    options?: VoiceConversationOptions,
  ) => Promise<void>
  startParaformerVoiceConversation: (options?: VoiceConversationOptions) => Promise<void>
  startSenseVoiceVoiceConversation: (options?: VoiceConversationOptions) => Promise<void>
  startTencentAsrConversation: (options?: VoiceConversationOptions) => Promise<void>
  startApiVoiceConversation: (options?: VoiceConversationOptions) => Promise<void>
}

export type VoiceLifecycle = {
  scheduleVoiceRestart: (statusText?: string, delay?: number, force?: boolean) => void
  speakAssistantReply: (text: string, shouldResumeContinuousVoice: boolean) => Promise<void>
  beginStreamingSpeechReply: (
    shouldResumeContinuousVoice: boolean,
  ) => StreamingSpeechOutputController | null
  toggleVoiceConversation: () => void
  startVoiceConversation: (options?: VoiceConversationOptions) => void
  stopVoiceConversation: () => void
}

export type VoiceTestEntries = {
  testSpeechInputConnection: (draftSettings: AppSettings) => Promise<VoiceDiagnosticResult>
  probeSpeechOutputPlaybackStart: (
    draftSettings: AppSettings,
    text: string,
  ) => Promise<void>
  testSpeechOutputReadiness: (
    draftSettings: AppSettings,
    options?: { playSample?: boolean; sampleText?: string },
  ) => Promise<VoiceDiagnosticResult>
  runAudioSmokeTest: (draftSettings: AppSettings) => Promise<VoiceDiagnosticResult>
}

// ── Mutable slot holders for late binding ──────────────────────────────────

// Plain objects with a `current` field — same shape as a ref so consumers can
// destructure naturally.  These get populated as the factories run; bindings
// reference `holder.current!.method(...)` lazily so the cycle works.
export type Holder<T> = { current: T | null }

/**
 * Extract Holder.current and assert non-null before returning — the return
 * type is T instead of T | null, so that `const bindings = expectHolderValue(...)`
 * inside a factory won't lose narrowing when used in nested closures.
 * (A plain `const x = holder.current; if (!x) throw` can lose narrowing inside
 * nested async function closures, producing a bunch of "possibly null" errors.)
 */
export function expectHolderValue<T>(holder: Holder<T>, message: string): T {
  if (holder.current === null) {
    throw new Error(message)
  }
  return holder.current
}

// ── The bag itself ──────────────────────────────────────────────────────────

export type VoiceRuntimeBag = {
  ctx: UseVoiceContext
  refs: VoiceRefs
  setters: VoiceSetters
  hookCallbacks: VoiceHookCallbacks
  hearingRuntime: HearingRuntime
  voiceBus: VoiceBus
  // Cross-factory holders — populated as createXxx(bag) runs.
  bindingsHolder: Holder<VoiceBindings>
  enginesHolder: Holder<VoiceEngines>
  lifecycleHolder: Holder<VoiceLifecycle>
  // Tunables (constants from useVoice)
  tunables: {
    voiceTranscriptDedupWindowMs: number
    maxContinuousNoSpeechRestarts: number
    browserTtsLipsyncIntervalMs: number
    audioTtsAnalyserFftSize: number
  }
}
